<?php
// auto-generated by sfPropelCrud
// date: 2009/11/13 18:39:30
?>
<h1>updates</h1>
<?php use_helper('Javascript'); ?>
<?php include_partial('global/topAction'); ?>

<table class="list">
<thead>
<tr>
  <th width="70">Id</th>
  <th>Description</th>
  <th width="70">Status</th>
  <th width="70">Created at</th>
  <th width="85">Action</th>
</tr>
</thead>
<tbody>
<?php foreach ($updatess as $updates): ?>
	<tr class="">
    <td><?php echo link_to($updates->getId(), 'updates/edit?id='.$updates->getId()) ?></td>
    <td>
			<span id="edit_me_description_<?php echo $updates->getId() ?>"><?php echo $updates->getDescription() ?></span>
			<?php echo input_in_place_editor_tag('edit_me_description_'.$updates->getId(), 'updates/editInLine?attribute=Description&id='.$updates->getId(), array(
			  'cols'        => 80,
			  'rows'        => 3,
			)) ?>
    </td>
    <td id="active_<?php echo $updates->getId(); ?>">
    	<?php
				if($updates->getStatus() == 'D'){
					$lnkName = 'Deactive';
					$status = 'D';
				}else{
					$lnkName = 'Active';
					$status = 'A';
				}
				echo link_to_remote($lnkName,	array('update' => 'active_'.$updates->getId(),'url' => '/updates/activation?id='.$updates->getId().'&status='.$status));
				//echo ($files->getStatus()=='A' ? 'Active' : 'Deactive');
    	?>
    </td>
    <td><?php echo date('d-M-y h:s',strtotime($updates->getCreatedAt())) ?></td>
   	<td class="action"><?php include_partial('global/myaction',array('id' => $updates->getId())); ?></td>
	</tr>
<?php endforeach; ?>
</tbody>
</table>

	<?php
		$sort = '';
		$pageNum = myUser::pageNavigate($pager,sfConfig::get('app_webpath').'/updates/list/page/');
		if($pageNum){
	?>
		<div class="pgn">
			<?php echo $pageNum; ?>
			<?php
				echo form_tag('updates/list','METHOD=GET');
				echo 'Jump to Page '.input_tag('page','','size=3');
				echo submit_tag('Go&raquo;','');
				echo '</form>';
			?>
		</div>
	<?php } ?>

<?php echo link_to ('create', 'updates/create') ?>
