<?php
// auto-generated by sfPropelCrud
// date: 2009/07/22 19:29:36
?>
<?php

/**
 * sites actions.
 *
 * @package    
 * @subpackage sites
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class deletethumbAction extends sfAction
{
  public function execute()
  {
    $files = FilesPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($files);

		$thumbServer = 'sft'.ceil($files->getId()/500);

		if(is_file(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/small_'.$files->getId().'.jpg')){
			unlink(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/small_'.$files->getId().'.jpg');
		}

		if(is_file(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/mid_'.$files->getId().'.jpg')){
			unlink(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/mid_'.$files->getId().'.jpg');
		}

		if(is_file(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/thumb_'.$files->getId().'.jpg')){
			unlink(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/thumb_'.$files->getId().'.jpg');
		}

		if(is_file(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/animate_'.$files->getId().'.gif')){
			unlink(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/animate_'.$files->getId().'.gif');
		}
		return true;
	}

	public function handleError()
	{
 		deleteAction::execute();
 		return sfView::NONE;
	}

}
