<?php
// auto-generated by sfPropelCrud
// date: 2009/08/28 17:35:10
?>
<?php use_helper('Javascript') ?>
<h1>File Manager</h1>
<table>
<tbody>
<tr>
	<th><?php	echo 'copy file from url:&nbsp;'; ?></th>
	<td><?php 
		echo form_tag('fm/url');
		echo input_hidden_tag('dir_path', $dir_path);
		echo 'Url: '.input_tag('url_path', '',array('size'=>70,'onblur'=>'var tt=this.value; tt = tt.split("/"); document.getElementById(\'rename_file_name\').value=tt.pop()'));
		echo '<br/>Rename: '.input_tag('rename_file_name', '',array('size'=>30));
		echo submit_tag('copy files',array('onclick'=>'if(document.getElementById(\'rename_file_name\').value==\'\') return false; if(document.getElementById(\'url_path\').value==\'\') return false;'));
		echo '</form>'; ?></td>
	<th><?php	echo 'Create Directory:&nbsp;'; ?></th>
	<td><?php 
		echo form_tag('fm/mkdir');
		echo input_hidden_tag('dir_path', $dir_path);
		echo input_tag('dir_name', '',array('size'=>20));
		echo submit_tag('Create Dir',array('onclick'=>'if(document.getElementById(\'dir_name\').value==\'\') return false;'));
		echo '</form>';
		?></td>
</tr>
</tbody>
</table>

<hr/>

<?php
/*
* Print Navigation Path
*/
echo '<b>Path:</b> ';
$pathArray = explode('/',$dir_path);
$dpath='';
array_shift($pathArray);
$c = array_pop($pathArray);
if(count($pathArray))
foreach($pathArray as $value){
	$dpath = $dpath.'/'.$value;
	echo link_to($value,'fm/index?navigation='.base64_encode($dpath)).' &raquo; ';
}
echo $c;
?>

<?php echo form_tag('fm/index',array('name'=>'Files', 'enctype'=>'multipart/form-data')) ?>
<table>
<tbody>
<tr>
	<th><?php	echo 'Browse Directory Path:&nbsp;'; ?></th>
	<td><?php echo input_tag('dir_path', $dir_path, array('size'=>70)); ?></td>
</tr>
<tr>
	<th><?php	echo ' Show me files '; ?></th>
	<td><?php echo submit_tag('show files') ?></td>
</tr>
</tbody>
</table>
</form>

<?php echo form_tag('fm/index','id=gForm') ?>
<?php	echo input_hidden_tag('dir_path', $dir_path); ?>
<?php
if($filesSelectedNow == true){
	$flist=$fileNewName='';
	echo '<table class="list">';
	foreach($files as $key=>$value){
	  //echo $value;
	  $flist .= "'".$value."', ";
	  $fileNewName .= "'".$rename_file_name[$key]."', ";
	  echo '<tr id="'.$value.'"><td id="get_'.$value.'"><a href="" onclick="makeDir(\''.$value.'\','.$category_id.',\''.$rename_file_name[$key].'\', \''.$removeFile.'\'); return false;">Get</a></td>';
	  echo '<td>'.base64_decode($value).'</td><td>'.$rename_file_name[$key].'</td></tr>';
	}
	echo '</table>';
	$flist = substr($flist,0,-2);
	$fileNewName = substr($fileNewName,0,-2);
}
elseif($files || $dirs){
	echo '<table class="list">';
	echo form_tag('files/dirCatch',array('name'=>'Dirs', 'enctype'=>'multipart/form-data'));
	foreach($dirs as $key=>$value){
	  echo '<tr>';
	  echo '<td>'.base64_decode($value).'</td>';
	  echo '<td>'.submit_tag(base64_decode($dir_name[$key]),array('value'=>$dir_path.'/'.base64_decode($dir_name[$key]),'name'=>'dir_path'));
	  ?>
  		<span id="edit_me_name_<?php echo md5($dir_name[$key]) ?>"><?php echo base64_decode($dir_name[$key]); ?></span>
		<?php echo input_in_place_editor_tag('edit_me_name_'.md5($dir_name[$key]), 'fm/rename?dir_path='.urlencode(base64_encode($dir_path)).'&file='.urlencode($dir_name[$key]), array(
		  'cols'        => 40,
		  'rows'        => 1,
		));
	  echo '</td>';
	  echo '<td>';
  	echo '&nbsp;'.link_to('[[zip]]', 'fm/zip?dir_path='.urlencode(base64_encode($dir_path)).'&dir='.urlencode(base64_encode($dir_path.'/'.base64_decode($dir_name[$key]))).'&dirName='.urlencode($dir_name[$key]) );
	  echo '</td><td>';
  	echo link_to('[[delete]]', 'fm/delete?dir_path='.urlencode(base64_encode($dir_path)).'&file='.urlencode(base64_encode($dir_path.'/'.base64_decode($dir_name[$key])) ));
	  echo '</td>';
	  echo '</tr>';
	}
	echo '</form>';
	foreach($files as $key=>$value){
		echo '<tr>';
	  echo '<td>'.label_for('',base64_decode($value));
	  echo '</td><td>';
//	  	echo base64_decode($rename_file_name[$key]);
	  	?>
		<span id="edit_me_name_<?php echo md5($rename_file_name[$key]) ?>"><?php echo base64_decode($rename_file_name[$key]); ?></span>
		<?php echo input_in_place_editor_tag('edit_me_name_'.md5($rename_file_name[$key]), 'fm/rename?dir_path='.urlencode(base64_encode($dir_path)).'&file='.urlencode($rename_file_name[$key]), array(
		  'cols'        => 40,
		  'rows'        => 1,
		));
	  	echo ' - <b>'.myClass::formatSize(filesize($_SERVER['DOCUMENT_ROOT'].'/'.$dir_path.'/'.base64_decode($rename_file_name[$key]))).'</b>';
	  echo '</td><td>';
	  if(substr(base64_decode($rename_file_name[$key]),-4)=='.zip')
	  	echo link_to('[[unzip]]', 'fm/unzip?dir_path='.urlencode(base64_encode($dir_path)).'&file='.urlencode(base64_encode($dir_path.'/'.base64_decode($rename_file_name[$key])) ));
	  echo '</td><td>';
  		echo link_to('[[delete]]', 'fm/delete?dir_path='.urlencode(base64_encode($dir_path)).'&file='.urlencode(base64_encode($dir_path.'/'.base64_decode($rename_file_name[$key])) ));
	  echo '</td>';
		echo '</tr>';
	}
	echo '</table>';
	?>
<?php
}
?>
</form>
