default:
  http_metas:
    content-type: text/html

  metas:
    title:        MirchiLoft.Com &raquo; 
    robots:       index, follow
    language:     en

  stylesheets:    []

  javascripts:    []

  has_layout:     on
  layout:         layout

dev:
  metas:
    title:        dev-MirchiLoft.Com &raquo; 

mirchiloft:
  metas:
    title:        MirchiLoft.Com &raquo; 