<?php
// auto-generated by sfPropelCrud
// date: 2009/07/22 19:29:36
?>
<?php

/**
 * sites actions.
 *
 * @package    
 * @subpackage sites
 * @author     SKYiTech.com
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class deletethumbAction extends sfAction
{
  public function execute()
  {
    $category = CategoryPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($category);

		$thumbServer = 'c';

		if(is_file(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/'.$category->getId().'_0.jpg')){
			unlink(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/'.$category->getId().'_0.jpg');
		}
		if(is_file(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/'.$category->getId().'_1.jpg')){
			unlink(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/'.$category->getId().'_1.jpg');
		}
		if(is_file(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/'.$category->getId().'_2.jpg')){
			unlink(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/'.$category->getId().'_2.jpg');
		}
		if(is_file(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/'.$category->getId().'_3.jpg')){
			unlink(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/'.$category->getId().'_3.jpg');
		}
		if(is_file(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/'.$category->getId().'_4.jpg')){
			unlink(sfConfig::get('sf_upload_dir').'/thumb/'.$thumbServer.'/'.$category->getId().'_4.jpg');
		}

		return true;
	}

	public function handleError()
	{
 		deleteAction::execute();
 		return sfView::NONE;
	}

}
